name: 'GitHub Actions update package'

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.9'
        required: false
        type: string
      test_script:
        required: false
        type: string
      setup_mongo:
        default: false
        required: false
        type: boolean
      setup_redis:
          default: false
          required: false
          type: boolean
    secrets:
      pipy_registry_auth:
        required: false
      slack_webhook_url:
        description: "notify slack on github action result"
        required: false
      env_base64:
        required: false
jobs:
  # This workflow contains a single job called "build"
  package-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      env_base64: ${{ secrets.env_base64 }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup ENV
        if: ${{ env.env_base64 != '' }}
        run: echo ${{ env.env_base64 }} | base64 -d > .env
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: install pipenv
        run: pip3 install pipenv
      - name: install package
        run: |
          rm -f Pipfile.lock
          pipenv update --dev
        env:
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
      - name: Check files using the black formatter
        uses: psf/black@stable
        with:
          options: "."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
      - uses: supercharge/redis-github-action@1.4.0
        if: inputs.setup_redis
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        if: inputs.setup_mongo
      - name: Run test
        run: ${{ inputs.test_script }}
      - name: notify slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }} # required
        if: always()
