name: 'GitHub Actions update package'

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.9'
        required: false
        type: string
    secrets:
      pipy_registry_auth:
        required: false
      checkout_token:
        required: true
jobs:
  # This workflow contains a single job called "build"
  package-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      env_base64: ${{ secrets.env_base64 }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.checkout_token }}
      - name: Setup ENV
        if: ${{ env.env_base64 != '' }}
        run: echo ${{ env.env_base64 }} | base64 -d > .env
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: install pipenv
        run: pip3 install pipenv
      - name: install package
        run: |
          rm -f Pipfile.lock
          pipenv update --dev
        env:
          REGISTRY_AUTH: ${{ secrets.pipy_registry_auth }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          token: ${{ secrets.checkout_token }}
