name: update pre-commit

on:
  schedule:
    - cron: '0 21 1 * *'  #21st day of every month 1:00 am UTC time
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
    - name: update pre-commit packages
      run: pre-commit autoupdate
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update pre-commit packages
